export default {
    LIST_EMPLOYEES : 'LIST_EMPLOYEE',
    ADD_EMPLOYEE : 'ADD_EMPLOYEE',
    UPDATE_EMPLOYEE : 'UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE : 'DELETE_EMPLOYEE',
    SEARCH_EMPLOYEE : 'SEARCH_EMPLOYEE'
}
